version: 2.0

jobs:
    build:
        docker:
            - image: circleci/openjdk:8-jdk
            - image: circleci/postgres:9.4
              # Specify service dependencies here if necessary
              # CircleCI maintains a library of pre-built images
              # documented at https://circleci.com/docs/2.0/circleci-images/
              # - image: circleci/postgres:9.4
              # Specify service dependencies here if necessary
              # CircleCI maintains a library of pre-built images
              # documented at https://circleci.com/docs/2.0/circleci-images/
              # - image: circleci/postgres:9.4
              working_directory: ~/repo
            - environment:
              # Customize the JVM maximum heap limit
              MAVEN_OPTS: -Xmx3200m
              POSTGRES_DB: circle_test
        steps:

            - checkout

            - restore_cache:
                  key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

            - run: sudo apt install postgresql-client
            - run: mvn dependency:go-offline
            - run:
                name: Wait for Postgres to start
                command: dockerize -wait tcp://localhost:5432 -timeout 1m
            - run:
                name: Preapare db
                command: psql -h 127.0.0.1 -U postgres -c "CREATE USER username WITH PASSWORD 'password'; GRANT ALL PRIVILEGES ON DATABASE circle_test TO username;"

            - save_cache:
                  paths:
                      - ~/.m2
                  key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

            #runt test
            - run: mvn integration-test -Dspring.profiles.active=circleci

            - store_test_results:
                  path: target/surefire-reports

            - store_artifacts:
                  path: target/bookmanagement.jar
destination: libs

general:
    artifacts:
        - "build/reports/jacoco"

test:
    post:
        - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
        - bash <(curl -s https://codecov.io/bash)
